export const GET_DEPENDENCY_GRAPH = "GET_DEPENDENCY_GRAPH"
export const VIEW_NODE_DEPENDENCIES = "VIEW_NODE_DEPENDENCIES"
export const OPEN_NODE_RESOURCE = "OPEN_NODE_RESOURCE"
export const OPEN_NODE_RESOURCE_URL = "OPEN_NODE_RESOURCE_URL"
