import beautify = require('js-beautify');

/**
 * js-beautify options tuned for e-mail template bodies. This markup is typically
 * generated by a WYSIWYG editor: every fragment of text is wrapped in its own
 * `<span style="font-family:...;font-size:...">`, so the noise is in the content,
 * not the whitespace - no formatter makes it "pretty".
 *
 * Correctness comes first here: the formatted body is what gets written back on
 * save, so the formatting MUST NOT change how the e-mail renders. That means:
 *  - `wrap_line_length: 0` - never break a line inside an attribute or a text
 *    run (readability is handled by editor soft-wrap + the live preview instead).
 *  - js-beautify's default `inline` list is kept (NOT `inline: []`) so adjacent
 *    inline elements stay on one line; inserting a newline between `</span>` and
 *    `<span>` would add a rendered space.
 * Only block-level structure is re-indented; blank lines collapse to at most one.
 */
export const BODY_BEAUTIFY_OPTIONS: beautify.HTMLBeautifyOptions = {
    indent_size: 2,
    indent_char: ' ',
    wrap_line_length: 0,
    wrap_attributes: 'preserve',
    preserve_newlines: true,
    max_preserve_newlines: 1,
    end_with_newline: false,
    indent_inner_html: false,
};

/**
 * Pretty-print a notification template body. Kept free of any `vscode` import so
 * it can be unit-tested for render-stability.
 */
export function formatNotificationTemplateBody(html: string): string {
    return beautify.html(html, BODY_BEAUTIFY_OPTIONS);
}
